# slogan: chat next
# port: 3000
services:
  chatnext:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_CHATNEXT_3000
      - _APP_URL=$SERVICE_FQDN_CHATNEXT
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
      - TEAM_DOMAIN=$TEAM_DOMAIN

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

